Feature custom rules, simplified #1
atk4/validate pull request #2
Opened 2019-07-20 16:25 UTC by abbadon1334

#1 a simplified version of the previous PR

in place of write :
```
        $model = $model->newInstance();
        $model->addCondition($field, '=', $value);
        
        $action = $model->action('count');
        $count  = (int)$action->getOne();
                
        // if is loaded must be 1;
        if ($isLoaded && $count == 1) {
            return true;
        }
        
        // if is not loaded must be 0;
        if (!$isLoaded && $count == 0) {
            return true;
        }
```
can be used in validation definition like this :

```
$validator->rule('email', [ ['atk4_value_unique', $userModel] ]);
```

2019-07-20 16:50 UTC, abbadon1334 commented
@romaninsh i think this can be interesting to be integrated, but i have doubts on naming.

2019-08-22 17:44 UTC, romaninsh commented
@DarkSide666 was working on "Unique" property for fields, which would be doing exactly same, but it would also be on ATK Data level not in a validator.

There is an error in your logic.

 - client A has email "foo@bar.baz"
 - edit Client B, set his email to "foo@bar.baz" - will allow you to save.

You need this logic:

``` php
 $q-> addCondition('email', $value)
 if($loaded) $q->addCondition('id', '!=', $this->id);
if ($q->action('count') > 0) { fail }
```

2019-08-29 17:34 UTC, romaninsh requested changes
few things to take care of.

2019-08-29 17:34 UTC, romaninsh commented on src/Rules/ValueUniqueOther.php
> +                                ->addCondition($ref_model_field, '=', $value)
can you provide a real-life example (simple one), if you can't come up with a good one - then lets exclude the rule (as it wouldn't be helpful)

2019-08-29 17:34 UTC, romaninsh commented on src/Rules/ValueUniqueOther.php
> + * @example ['atk4_value_unique_other',$model,'field_name_to_check']
give full example here with real-life fields: $model->addField('..')->validate(...)

2022-02-06 15:13 UTC, abbadon1334 commented
i will rebuild essentials ones for 3.1 follow suggestion of Romans

2022-02-06 15:13 UTC, closed without merging